USE [master]
GO
/****** Object:  Database [DB20242000327]    Script Date: 03/27/2024 11:22:59 AM ******/
CREATE DATABASE [DB20242000327]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB20242000327', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB20242000327.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB20242000327_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB20242000327_log.ldf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DB20242000327] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
    EXEC [DB20242000327].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB20242000327] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB20242000327] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB20242000327] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB20242000327] NOT FOR LOAD
GO
USE [DB20242000327]
GO
/****** Object:  Table [dbo].[TB_ESPACIO]    Script Date: 03/27/2024 11:22:59 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_ESPACIO]
(
    [ESPACIO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NUMERO_ESPACIO] [varchar](50) NOT NULL,
    [NUMERO_PISO] [int] NOT NULL,
    [CAPACIDAD_HUESPEDES] [int] NOT NULL,
    [ESTADO] [varchar](50) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [DESCRIPCION] [varchar](200) NULL,
    [TIPO] [varchar](50) NOT NULL,
    [CATEGORIA] [varchar](50) NOT NULL,
    [ESPACIO_PADRE_ID] [int] NULL,
    [ESTADO_MANTENIMIENTO] [varchar](50) NULL,
    [FECHA_ULTIMA_LIMPIEZA] [datetime] NULL,
    [FECHA_ULTIMO_MANTENIMIENTO] [datetime] NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_ESPACIO] PRIMARY KEY CLUSTERED ([ESPACIO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_HUESPED]
(
    [HUESPED_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [APELLIDO] [varchar](100) NOT NULL,
    [TELEFONO] [varchar](50) NOT NULL,
    [EMAIL] [varchar](100) NOT NULL,
    [DNI] [varchar](20) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_HUESPED] PRIMARY KEY CLUSTERED ([HUESPED_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_PROVEEDOR]
(
    [PROVEEDOR_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [TELEFONO] [varchar](50) NOT NULL,
    [EMAIL] [varchar](100) NULL,
    [ESTADO_ACTIVO] [varchar](50) NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_PROVEEDOR] PRIMARY KEY CLUSTERED ([PROVEEDOR_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_PRODUCTO]
(
    [PRODUCTO_ID] [int] IDENTITY(1,1) NOT NULL,
    [PROVEEDOR_ID] [int] NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [PRECIO] [decimal](18, 2) NOT NULL,
    [CANTIDAD] [int] NOT NULL,
    [UNIDAD] [varchar](50) NOT NULL,
    [FECHA_VENCIMIENTO] [datetime] NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_PRODUCTO] PRIMARY KEY CLUSTERED ([PRODUCTO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_RESERVA]
(
    [RESERVA_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [ESPACIO_ID] [int] NOT NULL,
    [FECHA_ENTRADA] [datetime] NOT NULL,
    [FECHA_SALIDA] [datetime] NOT NULL,
    [FECHA_RESERVA] [datetime] NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    [ESTADO_RESERVA] [varchar](50) NOT NULL,
    [MONTO_TOTAL] [decimal](18, 2) NOT NULL,
    [MONTO_PAGADO] [decimal](18, 2) NOT NULL,
    [OBSERVACIONES] [varchar](500) NULL,
    [NUMERO_PERSONAS] [int] NOT NULL,
    [METODO_PAGO] [varchar](50) NULL,
    [CONCEPTO] [varchar](100) NULL,
    [CANTIDAD_UNIDADES] [int] NOT NULL,
    [SUBTOTAL] [decimal](18, 2) NOT NULL,
    [TARIFA] [decimal](18, 2) NOT NULL,
    [MONEDA] [varchar](10) NULL,
    [ESTADO_PAGO] [varchar](50) NULL,
    [TIPO_PAGO] [varchar](50) NULL,
    [PORCENTAJE_ADELANTO] [decimal](18, 2) NOT NULL,
    [PORCENTAJE_RESTANTE] [decimal](18, 2) NOT NULL,
    [PORCENTAJE_PAGADO] [decimal](18, 2) NOT NULL,
    [FECHA_INICIO] [datetime] NULL,
    [FECHA_FIN] [datetime] NULL,
    CONSTRAINT [PK_TB_RESERVA] PRIMARY KEY CLUSTERED ([RESERVA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_PAGO]
(
    [PAGO_ID] [int] IDENTITY(1,1) NOT NULL,
    [RESERVA_ID] [int] NOT NULL,
    [MONTO] [decimal](18, 2) NOT NULL,
    [METODO_PAGO] [varchar](50) NOT NULL,
    [ESTADO_PAGO] [varchar](50) NOT NULL,
    [FECHA_PAGO] [datetime] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_PAGO] PRIMARY KEY CLUSTERED ([PAGO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_COMPRA]
(
    [COMPRA_ID] [int] IDENTITY(1,1) NOT NULL,
    [PROVEEDOR_ID] [int] NOT NULL,
    [NUMERO_FACTURA_PROVEEDOR] [varchar](50) NULL,
    [FECHA_COMPRA] [datetime] NOT NULL,
    [TOTAL_COMPRA] [decimal](18, 2) NOT NULL,
    [ESTADO_COMPRA] [varchar](50) NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_COMPRA] PRIMARY KEY CLUSTERED ([COMPRA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_DETALLE_COMPRA]
(
    [DETALLE_COMPRA_ID] [int] IDENTITY(1,1) NOT NULL,
    [COMPRA_ID] [int] NOT NULL,
    [PRODUCTO_ID] [int] NOT NULL,
    [CANTIDAD] [int] NOT NULL,
    [COSTO_UNITARIO] [decimal](18, 2) NOT NULL,
    [SUBTOTAL] [decimal](18, 2) NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_DETALLE_COMPRA] PRIMARY KEY CLUSTERED ([DETALLE_COMPRA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_MANTENIMIENTO]
(
    [MANTENIMIENTO_ID] [int] IDENTITY(1,1) NOT NULL,
    [ESPACIO_ID] [int] NOT NULL,
    [DESCRIPCION] [varchar](500) NOT NULL,
    [ESTADO] [varchar](50) NOT NULL,
    [FECHA_INICIO] [datetime] NOT NULL,
    [FECHA_FIN] [datetime] NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_MANTENIMIENTO] PRIMARY KEY CLUSTERED ([MANTENIMIENTO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_INCIDENTE]
(
    [INCIDENTE_ID] [int] IDENTITY(1,1) NOT NULL,
    [ESPACIO_ID] [int] NOT NULL,
    [DESCRIPCION] [varchar](500) NOT NULL,
    [ESTADO] [varchar](50) NOT NULL,
    [FECHA_REPORTE] [datetime] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_INCIDENTE] PRIMARY KEY CLUSTERED ([INCIDENTE_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_USUARIO]
(
    [USUARIO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [APELLIDO] [varchar](100) NOT NULL,
    [TELEFONO] [varchar](50) NULL,
    [EMAIL] [varchar](100) NOT NULL,
    [CONTRASENA] [varchar](255) NOT NULL,
    [ROL] [varchar](50) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_USUARIO] PRIMARY KEY CLUSTERED ([USUARIO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_REPORTE]
(
    [REPORTE_ID] [int] IDENTITY(1,1) NOT NULL,
    [TITULO] [varchar](200) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [FECHA_GENERACION] [datetime] NOT NULL,
    [FORMATO] [varchar](50) NOT NULL,
    [PATH_ARCHIVO] [varchar](500) NULL,
    [USUARIO_ID] [int] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_REPORTE] PRIMARY KEY CLUSTERED ([REPORTE_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_SOLICITUD_MANTENIMIENTO]
(
    [SOLICITUD_MANTENIMIENTO_ID] [int] IDENTITY(1,1) NOT NULL,
    [ESPACIO_ID] [int] NOT NULL,
    [USUARIO_ID] [int] NOT NULL,
    [DESCRIPCION] [varchar](500) NOT NULL,
    [ESTADO] [varchar](50) NOT NULL,
    [FECHA_SOLICITUD] [datetime] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_SOLICITUD_MANTENIMIENTO] PRIMARY KEY CLUSTERED ([SOLICITUD_MANTENIMIENTO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_CONFIGURACION]
(
    [CONFIGURACION_ID] [int] IDENTITY(1,1) NOT NULL,
    [CLAVE] [varchar](100) NOT NULL,
    [VALOR] [varchar](500) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_CONFIGURACION] PRIMARY KEY CLUSTERED ([CONFIGURACION_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_LOG]
(
    [LOG_ID] [int] IDENTITY(1,1) NOT NULL,
    [USUARIO_ID] [int] NOT NULL,
    [ACCION] [varchar](100) NOT NULL,
    [DETALLE] [varchar](500) NULL,
    [FECHA] [datetime] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_CONFIGURACION] PRIMARY KEY CLUSTERED ([LOG_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_HISTORIAL_PAGO]
(
    [HISTORIAL_PAGO_ID] [int] IDENTITY(1,1) NOT NULL,
    [RESERVA_ID] [int] NOT NULL,
    [PAGO_ID] [int] NOT NULL,
    [MONTO] [decimal](18, 2) NOT NULL,
    [FECHA_REGISTRO] [datetime] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_HISTORIAL_PAGO] PRIMARY KEY CLUSTERED ([HISTORIAL_PAGO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_RESERVA_HUESPED]
(
    [RESERVA_HUESPED_ID] [int] IDENTITY(1,1) NOT NULL,
    [RESERVA_ID] [int] NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_RESERVA_HUESPED] PRIMARY KEY CLUSTERED ([RESERVA_HUESPED_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_RESERVA_ESPACIO]
(
    [RESERVA_ESPACIO_ID] [int] IDENTITY(1,4) NOT NULL,
    [RESERVA_ID] [int] NOT NULL,
    [ESPACIO_ID] [int] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_RESERVA_ESPACIO] PRIMARY KEY CLUSTERED ([RESERVA_ESPACIO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_HISTORIAL_ESTADO]
(
    [HISTORIAL_ESTADO_ID] [int] IDENTITY(1,1) NOT NULL,
    [RESERVA_ID] [int] NOT NULL,
    [ESTADO_ANTERIOR] [varchar](50) NOT NULL,
    [ESTADO_NUEVO] [varchar](50) NOT NULL,
    [FECHA_CAMBIO] [datetime] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_HISTORIAL_ESTADO] PRIMARY KEY CLUSTERED ([HISTORIAL_ESTADO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_HABITACION]
(
    [TIPO_HABITACION_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [PRECIO_BASE] [decimal](18, 2) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_HABITACION] PRIMARY KEY CLUSTERED ([TIPO_HABITACION_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_PAGO]
(
    [TIPO_PAGO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_PAGO] PRIMARY KEY CLUSTERED ([TIPO_PAGO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_ESPACIO]
(
    [TIPO_ESPACIO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_ESPACIO] PRIMARY KEY CLUSTERED ([TIPO_ESPACIO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_CATEGORIA_ESPACIO]
(
    [CATEGORIA_ESPACIO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_CATEGORIA_ESPACIO] PRIMARY KEY CLUSTERED ([CATEGORIA_ESPACIO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_MONEDA]
(
    [TIPO_MONEDA_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZAMIENTO] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_MONEDA] PRIMARY KEY CLUSTERED ([TIPO_MONEDA_ID] ASC)
) ON [CREATE] 
GO
CREATE TABLE [dbo].[TB_TIPO_DOCUMENTO]
(
    [TIPO_DOCUMENTO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_DOCUMENTO] PRIMARY KEY CLUSTERED ([TIPO_DOCUMENTO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_ESTADO]
(
    [TIPO_ESTADO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_ESTADO] PRIMARY KEY CLUSTERED ([TIPO_ESTADO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_ESTADO]
(
    [ESTADO_ID] [int] IDENTITY(1,1) NOT NULL,
    [TIPO_ESTADO_ID] [int] NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_ESTADO] PRIMARY KEY CLUSTERED ([ESTADO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_DOC_IDENTIDAD]
(
    [DOC_IDENTIDAD_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [TIPO_DOCUMENTO_ID] [int] NOT NULL,
    [NUMERO_DOCUMENTO] [varchar](50) NOT NULL,
    [FECHA_EXPIRACION] [datetime] NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_DOC_IDENTIDAD] PRIMARY KEY CLUSTERED ([DOC_IDENTIDAD_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_CONTACTO]
(
    [CONTACTO_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [TIPO_CONTACTO] [varchar](50) NOT NULL,
    [VALOR] [varchar](100) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_CONTACTO] PRIMARY KEY CLUSTERED ([CONTACTO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_HUESPED_RESERVA]
(
    [HUESPED_RESERVA_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [RESERVA_ID] [int] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_HUESPED_RESERVA] PRIMARY KEY CLUSTERED ([HUESPED_RESERVA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo.[TB_TIPO_CONTACTO]
(
    [TIPO_CONTACTO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_CONTACTO] PRIMARY KEY CLUSTERED ([TIPO_CONTACTO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_BANCO]
(
    [BANCO_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_BANCO] PRIMARY KEY CLUSTERED ([BANCO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TARJETA]
(
    [TARJETA_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [BANCO_ID] [int] NOT NULL,
    [NUMERO_TARJETA] [varchar](50) NOT NULL,
    [FECHA_EXPIRACION] [datetime] NOT NULL,
    [CVV] [varchar](10) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TARJETA] PRIMARY KEY CLUSTERED ([TARJETA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TARJETA_RESERVA]
(
    [TARJETA_RESERVA_ID] [int] IDENTITY(1,1) NOT NULL,
    [TARJETA_ID] [int] NOT NULL,
    [RESERVA_ID] [int] NOT NULL,
    [MONTO] [decimal](18, 2) NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TARJETA_RESERVA] PRIMARY KEY CLUSTERED ([TARJETA_RESERVA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_HUELLA]
(
    [TIPO_HUELLA_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_HUELLA] PRIMARY KEY CLUSTERED ([TIPO_HUELLA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_HUELLA]
(
    [HUELLA_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [TIPO_HUELLA_ID] [int] NOT NULL,
    [VALOR] [varchar](500) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_HUELLA] PRIMARY KEY CLUSTERED ([HUELLA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_FIRMA]
(
    [FIRMA_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [VALOR] [varchar](500) NOT NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_FIRMA] PRIMARY KEY CLUSTERED ([FIRMA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_HISTORIAL_CUENTA]
(
    [HISTORIAL_CUENTA_ID] [int] IDENTITY(1,1) NOT NULL,
    [HUESPED_ID] [int] NOT NULL,
    [ESTADO_ANTERIOR] [varchar](50) NOT NULL,
    [ESTADO_NUEVO] [varchar](50) NOT NULL,
    [FECHA_CAMBIO] [datetime] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_HISTORIAL_CUENTA] PRIMARY KEY CLUSTERED ([HISTORIAL_CUENTA_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_REPORTE_DETALLE]
(
    [REPORTE_DETALLE_ID] [int] IDENTITY(1,1) NOT NULL,
    [REPORTE_ID] [int] NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [VALOR] [varchar](500) NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_REPORTE_DETALLE] PRIMARY KEY CLUSTERED ([REPORTE_DETALLE_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_REPORTE_ESTADISTICO]
(
    [REPORTE_ESTADISTICO_ID] [int] IDENTITY(1,1) NOT NULL,
    [REPORTE_ID] [int] NOT NULL,
    [TIPO] [varchar](100) NOT NULL,
    [VALOR] [varchar](500) NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_REPORTE_ESTADISTICO] PRIMARY KEY CLUSTERED ([REPORTE_ESTADISTICO_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_REPORTE]
(
    [TIPO_REPORTE_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_REPORTE] PRIMARY KEY CLUSTERED ([TIPO_REPORTE_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_TIPO_REPORTE_DETALLE]
(
    [TIPO_REPORTE_DETALLE_ID] [int] IDENTITY(1,1) NOT NULL,
    [NOMBRE] [varchar](100) NOT NULL,
    [DESCRIPCION] [varchar](500) NULL,
    [ESTADO_ACTIVO] [bit] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_TIPO_REPORTE_DETALLE] PRIMARY KEY CLUSTERED ([TIPO_REPORTE_DETALLE_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_REPORTE_TIPO_REPORTE]
(
    [REPORTE_TIPO_REPORTE_ID] [int] IDENTITY(1,1) NOT NULL,
    [REPORTE_ID] [int] NOT NULL,
    [TIPO_REPORTE_ID] [int] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_REPORTE_TIPO_REPORTE] PRIMARY KEY CLUSTERED ([REPORTE_TIPO_REPORTE_ID] ASC)
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[TB_REPORTE_TIPO_REPORTE_DETALLE]
(
    [REPORTE_TIPO_REPORTE_DETALLE_ID] [int] IDENTITY(1,1) NOT NULL,
    [REPORTE_ID] [int] NOT NULL,
    [TIPO_REPORTE_DETALLE_ID] [int] NOT NULL,
    [FECHA_CREACION] [datetime] NULL,
    [FECHA_ACTUALIZACION] [datetime] NULL,
    CONSTRAINT [PK_TB_REPORTE_TIPO_REPORTE_DETALLE] PRIMARY KEY CLUSTERED ([REPORTE_TIPO_REPORTE_DETALLE_ID] ASC)
) ON [PRIMARY]
GO
-- Foreign Keys

ALTER TABLE [dbo].[TB_PRODUCTO]  WITH CHECK ADD  CONSTRAINT [FK_TB_PRODUCTO_TB_PROVEEDOR] FOREIGN KEY([PROVEEDOR_ID])
REFERENCES [dbo].[TB_PROVEEDOR] ([PROVEEDOR_ID])
GO
ALTER TABLE [dbo].[TB_PRODUCTO] CHECK CONSTRAINT [FK_TB_PRODUCTO_TB_PROVEEDOR]
GO
ALTER TABLE [dbo].[TB_RESERVA]  WITH CHECK ADD  CONSTRAINT [FK_TB_RESERVA_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_RESERVA] CHECK CONSTRAINT [FK_TB_RESERVA_TB_HUESPED]
GO
ALTER TABLE [dbo].[TB_RESERVA]  WITH CHECK ADD  CONSTRAINT [FK_TB_RESERVA_TB_ESPACIO] FOREIGN KEY([ESPACIO_ID])
REFERENCES [dbo].[TB_ESPACIO] ([ESPACIO_ID])
GO
ALTER TABLE [dbo].[TB_RESERVA] CHECK CONSTRAINT [FK_TB_RESERVA_TB_ESPACIO]
GO
ALTER TABLE [dbo].[TB_PAGO]  WITH CHECK ADD  CONSTRAINT [FK_TB_PAGO_TB_RESERVA] FOREIGN KEY([RESERVA_ID])
REFERENCES [dbo].[TB_RESERVA] ([RESERVA_ID])
GO
ALTER TABLE [dbo].[TB_PAGO] CHECK CONSTRAINT [FK_TB_PAGO_TB_RESERVA]
GO
ALTER TABLE [dbo].[TB_COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_TB_COMPRA_TB_PROVEEDOR] FOREIGN KEY([PROVEEDOR_ID])
REFERENCES [dbo].[TB_PROVEEDOR] ([PROVEEDOR_ID])
GO
ALTER TABLE [dbo].[TB_COMPRA] CHECK CONSTRAINT [FK_TB_COMPRA_TB_PROVEEDOR]
GO
ALTER TABLE [dbo].[TB_DETALLE_COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_TB_DETALLE_COMPRA_TB_COMPRA] FOREIGN KEY([COMPRA_ID])
REFERENCES [dbo].[TB_COMPRA] ([COMPRA_ID])
GO
ALTER TABLE [dbo].[TB_DETALLE_COMPRA] CHECK CONSTRAINT [FK_TB_DETALLE_COMPRA_TB_COMPRA]
GO
ALTER TABLE [dbo].[TB_DETALLE_COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_TB_DETALLE_COMPRA_TB_PRODUCTO] FOREIGN KEY([PRODUCTO_ID])
REFERENCES [dbo].[TB_PRODUCTO] ([PRODUCTO_ID])
GO
ALTER TABLE [dbo].[TB_DETALLE_COMPRA] CHECK CONSTRAINT [FK_TB_DETALLE_COMPRA_TB_PRODUCTO]
GO
ALTER TABLE [dbo].[TB_MANTENIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_TB_MANTENIMIENTO_TB_ESPACIO] FOREIGN KEY([ESPACIO_ID])
REFERENCES [dbo].[TB_ESPACIO] ([ESPACIO_ID])
GO
ALTER TABLE [dbo].[TB_MANTENIMIENTO] CHECK CONSTRAINT [FK_TB_MANTENIMIENTO_TB_ESPACIO]
GO
ALTER TABLE [dbo].[TB_INCIDENTE]  WITH CHECK ADD  CONSTRAINT [FK_TB_INCIDENTE_TB_ESPACIO] FOREIGN KEY([ESPACIO_ID])
REFERENCES [dbo].[TB_ESPACIO] ([ESPACIO_ID])
GO
ALTER TABLE [dbo].[TB_INCIDENTE] CHECK CONSTRAINT [FK_TB_INCIDENTE_TB_ESPACIO]
GO
ALTER TABLE [dbo].[TB_REPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TB_REPORTE_TB_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[TB_USUARIO] ([USUARIO_ID])
GO
ALTER TABLE [dbo].[TB_REPORTE] CHECK CONSTRAINT [FK_TB_REPORTE_TB_USUARIO]
GO
ALTER TABLE [dbo].[TB_SOLICITUD_MANTENIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_TB_SOLICITUD_MANTENIMIENTO_TB_ESPACIO] FOREIGN KEY([ESPACIO_ID])
REFERENCES [dbo].[TB_ESPACIO] ([ESPACIO_ID])
GO
ALTER TABLE [dbo].[TB_SOLICITUD_MANTENIMIENTO] CHECK CONSTRAINT [FK_TB_SOLICITUD_MANTENIMIENTO_TB_ESPACIO]
GO
ALTER TABLE [dbo].[TB_SOLICITUD_MANTENIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_TB_SOLICITUD_MANTENIMIENTO_TB_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[TB_USUARIO] ([USUARIO_ID])
GO
ALTER TABLE [dbo].[TB_SOLICITUD_MANTENIMIENTO] CHECK CONSTRAINT [FK_TB_SOLICITUD_MANTENIMIENTO_TB_USUARIO]
GO
ALTER TABLE [dbo].[TB_LOG]  WITH CHECK ADD  CONSTRAINT [FK_TB_LOG_TB_USUARIO] FOREIGN KEY([USUARIO_ID])
REFERENCES [dbo].[TB_USUARIO] ([USUARIO_ID])
GO
ALTER TABLE [dbo].[TB_LOG] CHECK CONSTRAINT [FK_TB_LOG_TB_USUARIO]
GO
ALTER TABLE [dbo].[TB_HISTORIAL_PAGO]  WITH CHECK ADD  CONSTRAINT [FK_TB_HISTORIAL_PAGO_TB_RESERVA] FOREIGN KEY([RESERVA_ID])
REFERENCES [dbo].[TB_RESERVA] ([RESERVA_ID])
GO
ALTER TABLE [dbo].[TB_HISTORIAL_PAGO] CHECK CONSTRAINT [FK_TB_HISTORIAL_PAGO_TB_RESERVA]
GO
ALTER TABLE [dbo].[TB_HISTORIAL_PAGO]  WITH CHECK ADD  CONSTRAINT [FK_TB_HISTORIAL_PAGO_TB_PAGO] FOREIGN KEY([PAGO_ID])
REFERENCES [dbo].[TB_PAGO] ([PAGO_ID])
GO
ALTER TABLE [dbo].[TB_HISTORIAL_PAGO] CHECK CONSTRAINT [FK_TB_HISTORIAL_PAGO_TB_PAGO]
GO
ALTER TABLE [dbo].[TB_RESERVA_HUESPED]  WITH CHECK ADD  CONSTRAINT [FK_TB_RESERVA_HUESPED_TB_RESERVA] FOREIGN KEY([RESERVA_ID])
REFERENCES [dbo].[TB_RESERVA] ([RESERVA_ID])
GO
ALTER TABLE [dbo].[TB_RESERVA_HUESPED] CHECK CONSTRAINT [FK_TB_RESERVA_HUESPED_TB_RESERVA]
GO
ALTER TABLE [dbo].[TB_RESERVA_HUESPED]  WITH CHECK ADD  CONSTRAINT [FK_TB_RESERVA_HUESPED_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_RESERVA_HUESPED] CHECK CONSTRAINT [FK_TB_RESERVA_HUESPED_TB_HUESPED]
GO
ALTER TABLE [dbo].[TB_RESERVA_ESPACIO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RESERVA_ESPACIO_TB_RESERVA] FOREIGN KEY([RESERVA_ID])
REFERENCES [dbo].[TB_RESERVA] ([RESERVA_ID])
GO
ALTER TABLE [dbo].[TB_RESERVA_ESPACIO] CHECK CONSTRAINT [FK_TB_RESERVA_ESPACIO_TB_RESERVA]
GO
ALTER TABLE [dbo.[TB_RESERVA_ESPACIO]  WITH CHECK ADD  CONSTRAINT [FK_TB_RESERVA_ESPACIO_TB_ESPACIO] FOREIGN KEY([ESPACIO_ID])
REFERENCES [dbo].[TB_ESPACIO] ([ESPACIO_ID])
GO
ALTER TABLE [dbo].[TB_RESERVA_ESPACIO] CHECK CONSTRAINT [FK_TB_RESERVA_ESPACIO_TB_ESPACIO]
GO
ALTER TABLE [dbo].[TB_HISTORIAL_ESTADO]  WITH CHECK ADD  CONSTRAINT [FK_TB_HISTORIAL_ESTADO_TB_RESERVA] FOREIGN KEY([RESERVA_ID])
REFERENCES [dbo].[TB_RESERVA] ([RESERVA_ID])
GO
ALTER TABLE [dbo].[TB_HISTORIAL_ESTADO] CHECK CONSTRAINT [FK_TB_HISTORIAL_ESTADO_TB_RESERVA]
GO
ALTER TABLE [dbo].[TB_DOC_IDENTIDAD]  WITH CHECK ADD  CONSTRAINT [FK_TB_DOC_IDENTIDAD_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_DOC_IDENTIDAD] CHECK CONSTRAINT [FK_TB_DOC_IDENTIDAD_TB_HUESPED]
GO
ALTER TABLE [dbo].[TB_DOC_IDENTIDAD]  WITH CHECK ADD  CONSTRAINT [FK_TB_DOC_IDENTIDAD_TB_TIPO_DOCUMENTO] FOREIGN KEY([TIPO_DOCUMENTO_ID])
REFERENCES [dbo].[TB_TIPO_DOCUMENTO] ([TIPO_DOCUMENTO_ID])
GO
ALTER TABLE [dbo].[TB_DOC_IDENTIDAD] CHECK CONSTRAINT [FK_TB_DOC_IDENTIDAD_TB_TIPO_DOCUMENTO]
GO
ALTER TABLE [dbo].[TB_CONTACTO]  WITH CHECK ADD  CONSTRAINT [FK_TB_CONTACTO_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_CONTACTO] CHECK CONSTRAINT [FK_TB_CONTACTO_TB_HUESPED]
GO
ALTER TABLE [dbo].[TB_TARJETA]  WITH CHECK ADD  CONSTRAINT [FK_TB_TARJETA_TB_BANCO] FOREIGN KEY([BANCO_ID])
REFERENCES [dbo].[TB_BANCO] ([BANCO_ID])
GO
ALTER TABLE [dbo].[TB_TARJETA] CHECK CONSTRAINT [FK_TB_TARJETA_TB_BANCO]
GO
ALTER TABLE [dbo].[TB_TARJETA]  WITH CHECK ADD  CONSTRAINT [FK_TB_TARJETA_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_TARJETA] CHECK CONSTRAINT [FK_TB_TARJETA_TB_HUESPED]
GO
ALTER TABLE [dbo].[TB_TARJETA_RESERVA]  WITH CHECK ADD  CONSTRAINT [FK_TB_TARJETA_RESERVA_TB_TARJETA] FOREIGN KEY([TARJETA_ID])
REFERENCES [dbo].[TB_TARJETA] ([TARJETA_ID])
GO
ALTER TABLE [dbo].[TB_TARJETA_RESERVA] CHECK CONSTRAINT [FK_TB_TARJETA_RESERVA_TB_TARJETA]
GO
ALTER TABLE [dbo].[TB_TARJETA_RESERVA]  WITH CHECK ADD  CONSTRAINT [FK_TB_TARJETA_RESERVA_TB_RESERVA] FOREIGN KEY([RESERVA_ID])
REFERENCES [dbo].[TB_RESERVA] ([RESERVA_ID])
GO
ALTER TABLE [dbo].[TB_TARJETA_RESERVA] CHECK CONSTRAINT [FK_TB_TARJETA_RESERVA_TB_RESERVA]
GO
ALTER TABLE [dbo].[TB_HUELLA]  WITH CHECK ADD  CONSTRAINT [FK_TB_HUELLA_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_HUELLA] CHECK CONSTRAINT [FK_TB_HUELLA_TB_HUESPED]
\nGO
ALTER TABLE [dbo].[TB_HUELLA]  WITH CHECK ADD  CONSTRAINT [FK_TB_HUELLA_TB_TIPO_HUELLA] FOREIGN KEY([TIPO_HUELLA_ID])
REFERENCES [dbo].[TB_TIPO_HUELLA] ([TIPO_HUELLA_ID])
GO
ALTER TABLE [dbo].[TB_HUELLA] CHECK CONSTRAINT [FK_TB_HUELLA_TB_TIPO_HUELLA]
GO
ALTER TABLE [dbo].[TB_FIRMA]  WITH CHECK ADD  CONSTRAINT [FK_TB_FIRMA_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_FIRMA] CHECK CONSTRAINT [FK_TB_FIRMA_TB_HUESPED]
GO
ALTER TABLE [dbo].[TB_HISTORIAL_CUENTA]  WITH CHECK ADD  CONSTRAINT [FK_TB_HISTORIAL_CUENTA_TB_HUESPED] FOREIGN KEY([HUESPED_ID])
REFERENCES [dbo].[TB_HUESPED] ([HUESPED_ID])
GO
ALTER TABLE [dbo].[TB_HISTORIAL_CUENTA] CHECK CONSTRAINT [FK_TB_HISTORIAL_CUENTA_TB_HUESPED]
GO
ALTER TABLE [dbo].[TB_REPORTE_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_TB_REPORTE_DETALLE_TB_REPORTE] FOREIGN KEY([REPORTE_ID])
REFERENCES [dbo].[TB_REPORTE] ([REPORTE_ID])
GO
ALTER TABLE [dbo].[TB_REPORTE_DETALLE] CHECK CONSTRAINT [FK_TB_REPORTE_DETALLE_TB_REPORTE]
GO
ALTER TABLE [dbo].[TB_REPORTE_ESTADISTICO]  WITH CHECK ADD  CONSTRAINT [FK_TB_REPORTE_ESTADISTICO_TB_REPORTE] FOREIGN KEY([REPORTE_ID])
REFERMENTS [dbo].[TB_REPORTE]
([REPORTE_ID])
GO
ALTER TABLE [dbo].[TB_REPORTE_ESTADISTICO] CHECK CONSTRAINT [FK_TB_REPORTE_ESTADISTICO_TB_REPORTE]
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_TB_REPORTE] FOREIGN KEY([REPORTE_ID])
REFERENCES [dbo].[TB_REPORTE] ([REPORTE_ID])
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE] CHECK CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_TB_REPORTE]
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_TB_TIPO_REPORTE] FOREIGN KEY([TIPO_REPORTE_ID])
REFERENCES [dbo].[TB_TIPO_REPORTE] ([TIPO_REPORTE_ID])
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE] CHECK CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_TB_TIPO_REPORTE]
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_DETALLE_TB_REPORTE] FOREIGN KEY([REPORTE_ID])
REFERENCES [dbo].[TB_REPORTE] ([REPORTE_ID])
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE_DETALLE] CHECK CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_DETALLE_TB_REPORTE]
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_DETALLE_TB_TIPO_REPORTE_DETALLE] FOREIGN KEY([TIPO_REPORTE_DETALLE_ID])
REFERENCES [dbo].[TB_TIPO_REPORTE_DETALLE] ([TIPO_REPORTE_DETALLE_ID])
GO
ALTER TABLE [dbo].[TB_REPORTE_TIPO_REPORTE_DETALLE] CHECK CONSTRAINT [FK_TB_REPORTE_TIPO_REPORTE_DETALLE_TB_TIPO_REPORTE_DETALLE]
GO
